In [3]:
import pandas as pd
import numpy as np

In [17]:
np.random.seed( 100 ) 
dados = { "laranjas" : np.random.randint(1, 10, (5, )), "macas" : np.random.randint(1, 10, (5, ))} 
dados

{'laranjas': array([9, 9, 4, 8, 8], dtype=int32),
 'macas': array([1, 5, 3, 6, 3], dtype=int32)}

In [23]:
df = pd.DataFrame( dados, index = ["Joao", "Maria", "Jose", "Fatima", "Augusto" ] )
df

         laranjas  macas
Joao            9      1
Maria           9      5
Jose            4      3
Fatima          8      6
Augusto         8      3

In [27]:
df["macas"]["Fatima"]

np.int32(6)

In [31]:
df.iloc[1]

laranjas    9
macas       5
Name: Maria, dtype: int32

In [33]:
df.loc["Augusto"]

laranjas    8
macas       3
Name: Augusto, dtype: int32

In [41]:
df2 = pd.DataFrame.from_dict( dados, orient = "index", dtype=np.float32 )
df2

            0    1    2    3    4
laranjas  9.0  9.0  4.0  8.0  8.0
macas     1.0  5.0  3.0  6.0  3.0

In [53]:
df3 = pd.read_csv("C:\\git\\dados\\nlp\\medium_data.csv", index_col = 0)
df3

,url,title,subtitle,image,claps,responses,reading_time,publication,date
id,,,,,,,,,
1,https://towardsdatascience.com/a-beginners-gui...,A Beginner’s Guide to Word Embedding with Gens...,NaN,1.png,850,8,8,Towards Data Science,2019-05-30
2,https://towardsdatascience.com/hands-on-graph-...,Hands-on Graph Neural Networks with PyTorch & ...,NaN,2.png,1100,11,9,Towards Data Science,2019-05-30
3,https://towardsdatascience.com/how-to-use-ggpl...,How to Use ggplot2 in Python,A Grammar of Graphics for Python,3.png,767,1,5,Towards Data Science,2019-05-30
4,https://towardsdatascience.com/databricks-how-...,Databricks: How to Save Files in CSV on Your L...,When I work on Python projects dealing…,4.jpeg,354,0,4,Towards Data Science,2019-05-30
5,https://towardsdatascience.com/a-step-by-step-...,A Step-by-Step Implementation of Gradient Desc...,One example of building neural…,5.jpeg,211,3,4,Towards Data Science,2019-05-30
...,...,...,...,...,...,...,...,...,...
6504,https://medium.com/better-marketing/we-vs-i-ho...,“We” vs “I” — How Should You Talk About Yourse...,Basic copywriting choices with a big…,6504.jpg,661,6,6,Better Marketing,2019-12-05
6505,https://medium.com/better-marketing/how-donald...,How Donald Trump Markets Himself,Lessons from who might be the most popular bra...,6505.jpeg,189,1,5,Better Marketing,2019-12-05
6506,https://medium.com/better-marketing/content-an...,Content and Marketing Beyond Mass Consumption,How to acquire customers without wasting money...,6506.jpg,207,1,8,Better Marketing,2019-12-05
6507,https://medium.com/better-marketing/5-question...,5 Questions All Copywriters Should Ask Clients...,Save time and effort by…,6507.jpg,253,2,5,Better Marketing,2019-12-05
6508,https://medium.com/better-marketing/how-to-wri...,How To Write a Good Business Blog Post,An A-to-Z guide for non-writers,6508.jpg,147,0,9,Better Marketing,2019-12-05

In [45]:
df3.head()

,id,url,title,subtitle,image,claps,responses,reading_time,publication,date
0,1,https://towardsdatascience.com/a-beginners-gui...,A Beginner’s Guide to Word Embedding with Gens...,NaN,1.png,850,8,8,Towards Data Science,2019-05-30
1,2,https://towardsdatascience.com/hands-on-graph-...,Hands-on Graph Neural Networks with PyTorch & ...,NaN,2.png,1100,11,9,Towards Data Science,2019-05-30
2,3,https://towardsdatascience.com/how-to-use-ggpl...,How to Use ggplot2 in Python,A Grammar of Graphics for Python,3.png,767,1,5,Towards Data Science,2019-05-30
3,4,https://towardsdatascience.com/databricks-how-...,Databricks: How to Save Files in CSV on Your L...,When I work on Python projects dealing…,4.jpeg,354,0,4,Towards Data Science,2019-05-30
4,5,https://towardsdatascience.com/a-step-by-step-...,A Step-by-Step Implementation of Gradient Desc...,One example of building neural…,5.jpeg,211,3,4,Towards Data Science,2019-05-30

In [49]:
df3.tail(10)

,id,url,title,subtitle,image,claps,responses,reading_time,publication,date
6498,6499,https://medium.com/datadriveninvestor/healthca...,Greenhouse Healthcare,NaN,6499.png,50,0,9,Data Driven Investor,2019-12-05
6499,6500,https://medium.com/datadriveninvestor/innovato...,Innovator’s Journal: Pitching To Perfection,NaN,6500.jpg,4,0,2,Data Driven Investor,2019-12-05
6500,6501,https://medium.com/datadriveninvestor/a-word-o...,A Word on the Controversy of Facebook’s Libra,Will Facebook be able to successfully launch L...,6501.jpeg,149,0,4,Data Driven Investor,2019-12-05
6501,6502,https://medium.com/datadriveninvestor/blockcha...,Blockchain: A Catalyst to Profitability in the...,NaN,6502.png,61,0,5,Data Driven Investor,2019-12-05
6502,6503,https://medium.com/better-marketing/ui-ux-tren...,The Top 6 UI and UX Trends for 2020,What’s coming to design in the new year?,6503.png,597,3,3,Better Marketing,2019-12-05
6503,6504,https://medium.com/better-marketing/we-vs-i-ho...,“We” vs “I” — How Should You Talk About Yourse...,Basic copywriting choices with a big…,6504.jpg,661,6,6,Better Marketing,2019-12-05
6504,6505,https://medium.com/better-marketing/how-donald...,How Donald Trump Markets Himself,Lessons from who might be the most popular bra...,6505.jpeg,189,1,5,Better Marketing,2019-12-05
6505,6506,https://medium.com/better-marketing/content-an...,Content and Marketing Beyond Mass Consumption,How to acquire customers without wasting money...,6506.jpg,207,1,8,Better Marketing,2019-12-05
6506,6507,https://medium.com/better-marketing/5-question...,5 Questions All Copywriters Should Ask Clients...,Save time and effort by…,6507.jpg,253,2,5,Better Marketing,2019-12-05
6507,6508,https://medium.com/better-marketing/how-to-wri...,How To Write a Good Business Blog Post,An A-to-Z guide for non-writers,6508.jpg,147,0,9,Better Marketing,2019-12-05

In [51]:
df3.describe()

                id         claps  reading_time
count  6508.000000   6508.000000   6508.000000
mean   3254.500000    311.076060      6.134911
std    1878.842108    950.789896      3.231918
min       1.000000      0.000000      0.000000
25%    1627.750000     54.000000      4.000000
50%    3254.500000    115.000000      5.000000
75%    4881.250000    268.250000      7.000000
max    6508.000000  38000.000000     55.000000

In [57]:
df3.loc[1]

url             https://towardsdatascience.com/a-beginners-gui...
title           A Beginner’s Guide to Word Embedding with Gens...
subtitle                                                      NaN
image                                                       1.png
claps                                                         850
responses                                                       8
reading_time                                                    8
publication                                  Towards Data Science
date                                                   2019-05-30
Name: 1, dtype: object

In [59]:
df3.iloc[0]

url             https://towardsdatascience.com/a-beginners-gui...
title           A Beginner’s Guide to Word Embedding with Gens...
subtitle                                                      NaN
image                                                       1.png
claps                                                         850
responses                                                       8
reading_time                                                    8
publication                                  Towards Data Science
date                                                   2019-05-30
Name: 1, dtype: object

In [63]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6508 entries, 1 to 6508
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   url           6508 non-null   object
 1   title         6508 non-null   object
 2   subtitle      3479 non-null   object
 3   image         6361 non-null   object
 4   claps         6508 non-null   int64
 5   responses     6508 non-null   object
 6   reading_time  6508 non-null   int64
 7   publication   6508 non-null   object
 8   date          6508 non-null   object
dtypes: int64(2), object(7)
memory usage: 766.5+ KB

In [65]:
df3.shape

(6508, 9)

In [67]:
np.random.seed( 32 ) 
dados1 = { "laranjas" : np.random.randint(1, 10, (5, )), "macas" : np.random.randint(1, 10, (5, ))} 
dados1

{'laranjas': array([8, 6, 7, 9, 4], dtype=int32),
 'macas': array([8, 4, 6, 5, 2], dtype=int32)}

In [69]:
np.random.seed( 64 ) 
dados2 = { "peras" : np.random.randint(1, 10, (5, )), "bananas" : np.random.randint(1, 10, (5, ))} 
dados2

{'peras': array([5, 7, 8, 7, 7], dtype=int32),
 'bananas': array([2, 5, 4, 6, 1], dtype=int32)}

In [73]:
df1 = pd.DataFrame( dados1 )
df2 = pd.DataFrame( dados2 )

In [75]:
df1

   laranjas  macas
0         8      8
1         6      4
2         7      6
3         9      5
4         4      2

In [77]:
df2

   peras  bananas
0      5        2
1      7        5
2      8        4
3      7        6
4      7        1

In [95]:
df3 = pd.concat( [df1, df2 ], axis = 1 )
df3

   laranjas  macas  peras  bananas
0         8      8      5        2
1         6      4      7        5
2         7      6      8        4
3         9      5      7        6
4         4      2      7        1

In [91]:
# df3.drop_duplicates()

   laranjas  macas  peras  bananas
0       8.0    8.0    NaN      NaN
1       6.0    4.0    NaN      NaN
2       7.0    6.0    NaN      NaN
3       9.0    5.0    NaN      NaN
4       4.0    2.0    NaN      NaN
0       NaN    NaN    5.0      2.0
1       NaN    NaN    7.0      5.0
2       NaN    NaN    8.0      4.0
3       NaN    NaN    7.0      6.0
4       NaN    NaN    7.0      1.0

In [97]:
df3

   laranjas  macas  peras  bananas
0         8      8      5        2
1         6      4      7        5
2         7      6      8        4
3         9      5      7        6
4         4      2      7        1

In [113]:
np.random.seed( 128 ) 
s1 = pd.Series(np.random.randint(1, 10, (5, )), name="ameixas")
s1

0    3
1    4
2    6
3    3
4    8
Name: ameixas, dtype: int32

In [115]:
df3["ameixas"] = s1
df3

   laranjas  macas  peras  bananas  ameixas
0         8      8      5        2        3
1         6      4      7        5        4
2         7      6      8        4        6
3         9      5      7        6        3
4         4      2      7        1        8

In [127]:
df3["metade_laranjas"]  = df3["laranjas"] / 2
df3

   laranjas  macas  peras  bananas  ameixas  metade_laranjas
0         8      8      5        2        3              4.0
1         6      4      7        5        4              3.0
2         7      6      8        4        6              3.5
3         9      5      7        6        3              4.5
4         4      2      7        1        8              2.0

In [125]:
del df3["metade_laranjas"]
df3

   laranjas  macas  peras  bananas  ameixas
0         8      8      5        2        3
1         6      4      7        5        4
2         7      6      8        4        6
3         9      5      7        6        3
4         4      2      7        1        8

In [131]:
df3.pop("metade_laranjas")
df3

   laranjas  macas  peras  bananas  ameixas
0         8      8      5        2        3
1         6      4      7        5        4
2         7      6      8        4        6
3         9      5      7        6        3
4         4      2      7        1        8

In [139]:
df3[["laranjas", "macas"]][2:4]

   laranjas  macas
2         7      6
3         9      5

In [163]:
df4 = pd.concat( [df3, df3] )
# df4.reindex([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
df4.reset_index()

   index  laranjas  macas  peras  bananas  ameixas
0      0         8      8      5        2        3
1      1         6      4      7        5        4
2      2         7      6      8        4        6
3      3         9      5      7        6        3
4      4         4      2      7        1        8
5      0         8      8      5        2        3
6      1         6      4      7        5        4
7      2         7      6      8        4        6
8      3         9      5      7        6        3
9      4         4      2      7        1        8

In [147]:
df4.drop(2)

   laranjas  macas  peras  bananas  ameixas
0         8      8      5        2        3
1         6      4      7        5        4
3         9      5      7        6        3
4         4      2      7        1        8
0         8      8      5        2        3
1         6      4      7        5        4
3         9      5      7        6        3
4         4      2      7        1        8

In [165]:
df4

   laranjas  macas  peras  bananas  ameixas
0         8      8      5        2        3
1         6      4      7        5        4
2         7      6      8        4        6
3         9      5      7        6        3
4         4      2      7        1        8
0         8      8      5        2        3
1         6      4      7        5        4
2         7      6      8        4        6
3         9      5      7        6        3
4         4      2      7        1        8

In [173]:
def rever_valores( numero_laranjas ):
    if numero_laranjas < 5:
        return numero_laranjas * 4
    else:
        return numero_laranjas * 2

In [179]:
df4["macas_recalculadas"] = df4["macas"].apply(rever_valores)

In [181]:
df4

   laranjas  macas  peras  bananas  ameixas  macas_recalculadas
0         8      8      5        2        3                  16
1         6      4      7        5        4                  16
2         7      6      8        4        6                  12
3         9      5      7        6        3                  10
4         4      2      7        1        8                   8
0         8      8      5        2        3                  16
1         6      4      7        5        4                  16
2         7      6      8        4        6                  12
3         9      5      7        6        3                  10
4         4      2      7        1        8                   8